version: '3'
services:
  protoshock-server:
    image: protoshock/protoshock-server:main # For ARM64/ARMV6/ARMV7 Change to ARCH-main Example: armv64-main
    container_name: Protoshock
    ports:
      - "8880:8880"
    environment:
      - expostGC=true
      - debugType=full
      - useHTTPS=true
      - httpsCert='/path/to/ssl/certificate'
      - httpsKey='/path/to/ssl/private_key'
      - port=8880
    restart: always