version: '3'
services:
  protoshock-server:
    build:
      context: .
      dockerfile: Dev-Dockerfile # For ARM64/ARMV6/ARMV7 Change to ARCH-Dockerfile
    image: protoshock-server
    container_name: Protoshock-Server
    ports:
      - "8880:8880"
    restart: always
