name: ci
on:
  push:
    branches:
      - 'main'
    paths:
      - "index.js"
      - "package*.json"
      - "assets/*"
      - "Dockerfile"
      - "Armv6-Dockerfile"
      - "Armv7-Dockerfile"
      - "Arm64-Dockerfile"
      - ".github/workflows/docker-image.yml"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
        include:
          - platform: linux/amd64
            image: protoshock/protoshock-server
            dockerfile: Dockerfile
            tag_suffix: latest
          - platform: linux/arm/v6
            image: protoshock/protoshock-server
            dockerfile: Armv6-Dockerfile
            tag_suffix: armv6
          - platform: linux/arm/v7
            image: protoshock/protoshock-server
            dockerfile: Armv7-Dockerfile
            tag_suffix: armv7
          - platform: linux/arm64
            image: protoshock/protoshock-server
            dockerfile: Arm64-Dockerfile
            tag_suffix: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}:${{ matrix.tag_suffix }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ matrix.image }}:${{ matrix.tag_suffix }}
          labels: ${{ steps.meta.outputs.labels }}
